<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-3NPM5AHR" failures="0" tests="2" name="com.sourcepro.Login.LoginIndex" time="21.120" errors="1" timestamp="2022-06-20T10:59:21 IST" skipped="0">
  <testcase classname="com.sourcepro.Login.LoginIndex" name="login" time="20.597"/>
  <system-out>
    <![CDATA[Open URL : http://192.168.0.147:8074/</br>
Do login with valid email and password.</br>
Do login with valid username and password.</br>
Entered Connection String: Server=PC43\\SQLEXPRESS;Database=NH1QCCybAdmin280422;uid=sa;pwd=;Max Pool Size=1000;Connection TimeOut= 3000;</br>
Entered Email: super</br>
Entered Password: Name@642</br>
Select Company.</br>
Selected Company: SourcePro Infotech Pvt Ltd</br>
Select Location.</br>
Selected Location: CTPL Unit2</br>
Click on right arrow icon.</br>
<Strong><b>Login_Do Loginnnnnn is passed.</b></font></strong></br>]]>
  </system-out>
  <testcase classname="com.sourcepro.Login.LoginIndex" name="logout" time="0.523">
    <error message="Test name must not be null or empty" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Test name must not be null or empty
at com.aventstack.extentreports.util.Assert.notEmpty(Assert.java:12)
at com.aventstack.extentreports.ExtentTest.<init>(ExtentTest.java:96)
at com.aventstack.extentreports.ExtentTest.<init>(ExtentTest.java:117)
at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:231)
at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:245)
at com.sourcepro.reports.ExtentReport.createTest(ExtentReport.java:37)
at com.sourcepro.reports.ExtentReportListener.onTestStart(ExtentReportListener.java:29)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:106)
at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:277)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:638)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- logout -->
  <system-out>
    <![CDATA[<a href='../test-output/screenshots/finalScreenshot_20220620105920609.png' target='new'><img src='../test-output/screenshots/finalScreenshot_20220620105920609.png' width='200' height='100'/></a></br>
<Strong><b>Logout_Logout is failed.</b></font></strong></br>]]>
  </system-out>
</testsuite> <!-- com.sourcepro.Login.LoginIndex -->
